name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Process uploaded images
      run: |
        # Create media directories if they don't exist
        mkdir -p public/images/categories
        mkdir -p public/images/questions
        mkdir -p public/audio
        mkdir -p public/video

        # Process any media files in uploads/ folder (for future upload system)
        if [ -d "uploads" ]; then
          echo "Processing uploaded media files..."

          # Copy category images
          if [ -d "uploads/categories" ]; then
            cp -r uploads/categories/* public/images/categories/ 2>/dev/null || true
          fi

          # Copy question images
          if [ -d "uploads/questions" ]; then
            cp -r uploads/questions/* public/images/questions/ 2>/dev/null || true
          fi

          # Copy audio files
          if [ -d "uploads/audio" ]; then
            cp -r uploads/audio/* public/audio/ 2>/dev/null || true
          fi

          # Copy video files
          if [ -d "uploads/video" ]; then
            cp -r uploads/video/* public/video/ 2>/dev/null || true
          fi

          echo "Media files processed and moved to public/ directories"
        else
          echo "No uploads folder found - skipping media processing"
        fi

    - name: Build project
      run: npm run build

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAMAH_357F3 }}'
        projectId: lamah-357f3
        channelId: live